[workspace]
resolver = "3"
members = ["crates/keyless-core", "apps/desktop/src-tauri"]

[workspace.package]
version = "0.1.4"
edition = "2024"
repository = "https://github.com/DiegoCastroAlves/Keyless"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true

[profile.dev.package.argon2]
opt-level = 3
